#!/usr/bin/env python3
"""Export a trained policy to a Lua table the game can run.

The network is small enough to evaluate in Lua directly - forty thousand multiply-adds a
frame is nothing next to what the game is already doing - so nothing has to be running on
the side and no prediction has to cross a socket. A bridge to Python would add a round trip
to every decision, which for aiming is the one cost that cannot be paid.

    python3 export.py                 model.pt -> model.lua

What goes in the file is everything the module needs to reproduce featurisation exactly:
the weights, the normalisation the inputs were trained under, the held-item vocabulary, and
the scaling the look head's outputs were learned in. A module that builds its features even
slightly differently to this script gets silent nonsense, not an error, so the layout is
written out alongside the numbers for the Lua side to assert against.
"""

from __future__ import annotations

import sys
from pathlib import Path

import torch


def numbers(values) -> str:
    # Five significant figures: the difference against full precision is far below what
    # the inputs themselves are accurate to, and it nearly halves the file.
    return ",".join(f"{v:.5g}" for v in values)


def main() -> int:
    here = Path(__file__).parent
    source = here / "model.pt"
    target = here / "model.lua"

    if not source.exists():
        print(f"no {source} - train first")
        return 1

    bundle = torch.load(source, weights_only=False)
    state = bundle["state"]

    layers = []
    for name in ("trunk.0", "trunk.3", "move.0", "look", "jump", "attack"):
        weight = state[f"{name}.weight"]
        bias = state[f"{name}.bias"]
        layers.append((name.replace(".", "_"), weight, bias))

    vocab = bundle["vocab"]
    ordered = sorted(vocab.items(), key=lambda kv: kv[1])

    out = ["-- Generated by export.py. Weights for the in-game policy; do not edit by hand.",
           "-- Layout is asserted by the module: features must be built exactly as train.py does.",
           "return {"]
    out.append(f"\thistory = {bundle['history']},")
    out.append(f"\twidth = {bundle['width']},")
    out.append(f"\tnumeric = {len(bundle['numeric'])},")
    out.append(f"\theldSlots = {bundle['held_slots']},")
    out.append("\t-- Item types that get a slot of their own, in order. Anything else shares the last.")
    out.append("\tvocab = {" + ",".join(f"['{name}']={index + 1}" for name, index in ordered) + "},")
    out.append(f"\tmean = {{{numbers(bundle['mean'])}}},")
    out.append(f"\tstd = {{{numbers(bundle['std'])}}},")
    out.append(f"\tlookMean = {{{numbers(bundle['look_mean'])}}},")
    out.append(f"\tlookStd = {{{numbers(bundle['look_std'])}}},")

    for name, weight, bias in layers:
        rows, cols = weight.shape
        out.append(f"\t{name} = {{")
        out.append(f"\t\trows = {rows}, cols = {cols},")
        # Row major and flat: a Lua table of tables costs an index per element to walk, and
        # this is read once per frame.
        out.append(f"\t\tw = {{{numbers(weight.flatten().tolist())}}},")
        out.append(f"\t\tb = {{{numbers(bias.tolist())}}}")
        out.append("\t},")

    out.append("}")
    text = "\n".join(out) + "\n"
    target.write_text(text, encoding="utf-8")

    total = sum(w.numel() + b.numel() for _, w, b in layers)
    print(f"{target}  {len(text) / 1024:.0f} KB, {total:,} parameters")
    print(f"input width {layers[0][1].shape[1]} = {bundle['numeric']} numeric + {bundle['held_slots']} held + 1 self, "
          f"stacked {bundle['history']} deep, plus {bundle['history'] - 1} past actions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
